### PR TITLE
Added aniketsingh98571

### PR DESCRIPTION
**Pull request by aniketsingh98571**
@srinibasbiswal  Please review my PR, and do let me know if any changes required.

### CODE REVIEW

**Comment by srinibasbiswal** [comment]
Hi @aniketsingh98571 , Can you please give the full URL for images instead of local path.

**Comment by aniketsingh98571** [comment]
Which URL ? @srinibasbiswal

**Comment by srinibasbiswal** [comment]
@aniketsingh98571 For the images like the first image and social links please change the url to waw.github. 
For example : 
For the first image : current url : https://github.com/aniketsingh98571/Web_Development/blob/master/canva.png
expected url  : https://raw.githubusercontent.com/aniketsingh98571/Web_Development/master/canva.png

Check your markdown at https://uiwjs.github.io/react-md-editor/

**Comment by aniketsingh98571** [comment]
@srinibasbiswal  You have given the wrong name on your website, You have given Ayushi Mittal instead of Aniket Singh in my Profile readme. Please resolve this.

**Comment by srinibasbiswal** [comment]
@aniketsingh98571 Please hard reload. Sometimes, it's messing up. I am working on that. For now, hard reloading is resolving that.

**Comment by aniketsingh98571** [comment]
@srinibasbiswal  Done
And I have also added this to my profile

**Comment by srinibasbiswal** [comment]
@aniketsingh98571 Please create a new pull request

**Comment by aniketsingh98571** [comment]
@srinibasbiswal Please add the "Hacktoberfest" label to your repo and also add "Hacktoberfest-accepted" labels to the merged PR,
as the rules for Hacktoberfest have changed. It's a request to you to please add the "Hacktoberfest-accepted" label to my merged PR.

**Pull request merged**
