### PR TITLE
Added immayurpanchal github readme.md profile which adds profile in #1

### PR DESCRIPTION
**Pull request by immayurpanchal**

### CODE REVIEW

**Comment by immayurpanchal** [comment]
#1

**Comment by immayurpanchal** [comment]
Hi @srinibasbiswal , Thanks a lot for merging my PR. 

Please add required labels to this PR so that it will be eligible for hacktoberfest. 

Screenshot from 2020-10-04 00-18-08
Screenshot from 2020-10-04 00-17-53

**Comment by srinibasbiswal** [comment]
Hi @immayurpanchal , Yes I am aware of the new rules. I think I have added all the required tags. 
- In the repository topics, I have added the hacktoberfest tag.
tempsnip

- In the open issues, I have added the hacktoberfest tag.

Please let me know if I am missing somewhere.

Thanks

**Comment by immayurpanchal** [comment]
@srinibasbiswal , Thanks for reply. Actually, I'm contributing in another open source project and I saw the hacktoberfest-accepted tag applied for merged requests. Well, I'm not sure. I hope my contribution will help you. Please have a look at attached screenshot. It may can help us.

Screenshot from 2020-10-04 17-31-26

Can you please try adding labels as marked in the above screenshot here?

**Comment by srinibasbiswal** [comment]
Hi @immayurpanchal , though I am adding the tag but,  hacktoberfest-accepted tag is added to those PRs which cannot be merged now. It is an indication for the hacktoberfest team to tell them that though this PR is not merged, it can be counted towards hactoberfest contribution. As your PR is merged, it is not required to add the label anymore.

Thanks

**Pull request merged**
